// <auto-generated />
namespace OjayFood.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Product_FinalCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_FinalCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202203301040199_Product_FinalCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
