// <auto-generated />
namespace OjayFood.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Product_ImageData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_ImageData));
        
        string IMigrationMetadata.Id
        {
            get { return "202203291136046_Product_ImageData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
